// <auto-generated />
namespace Logixion.Domain.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UserDetailTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserDetailTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201711051425336_UserDetailTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
